# Site settings
title: Your Site Title
description: A brief description of your site
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Theme settings
remote_theme: dracula/gh-pages
plugins:
  - jekyll-remote-theme

# Dracula theme options
show_downloads: false
show_header: true # Optional: set to false to hide the header
# Optional color settings (cyan/green/orange/pink/purple/red/yellow)
colorspace: purple

# Build settings
markdown: kramdown
